// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuhchobyoxvrnoihkxzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1aGNob2J5b3h2cm5vaWhreHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTY1MDAsImV4cCI6MjA2MDk5MjUwMH0.0pPo2l2d05hgaG9sMt_ikQCMeCNgTbfohR5f-q2uYsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);